apiVersion: configsync.gke.io/v1beta1
kind: Repo
metadata:
  name: repo-sync
  namespace: gamestore
spec:
  sourceFormat: unstructured
  git:
    repo: git@github.com:Minraj1/anthos-config-management-samples.git
    branch: init
    dir: quickstart/multirepo/namespaces/gamestore
    auth: ssh
    secretRef:
      name: minrajsecret2
